export const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const API_BASE_URL = process.env.API_BASE_URL;

export const API_ROUTES = {
  CARS: {
    GET_CACHED_CARS: "/get-cached-cars",
    INVENTORY_CARS: "/cars",
  },
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
    VERIFY_EMAIL: "/verify-email",
    UPDATE_PASSWORD: "/change-password",
    FORGET_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  CARFAX: {
    CHECK_RECORDS: "https://carstat.dev/api/reports/check-records/:vin",
    BALANCE: "https://carstat.dev/api/reports/balance",
  },
  FILTERS: {
    MANUFACTURERS: "/manufacturers",
    MODEL: "/models",
    SAVE_FILTERS: "/save-filters",
    GET_SAVED_FILTERS: "/show-filters",
    DELETE_SAVED_FILTER: "/delete-filters",
    EDIT_FILTERS: "/edit-filters",
  },
  WISHLIST: {
    GET_WISHLIST: "/wishlist",
    REMOVE_FROM_WISHLIST: "/remove-from-wishlist",
  },
  TRANSACTION_HISTORY: {
    GET_TRANSACTION_HISTORY: "/show_transaction_history",
  },
  SHIPPING_COST: "/get-shipping-cost",
  PAYMENT: "/payment",
};

export const API_KEYS = {
  X_API_KEY: process.env.NEXT_PUBLIC_X_API_KEY || process.env.X_API_KEY,
} as const;

export const imageUrls = {
  carShipping: "https://servedby.auctionbidia.com/getad.img/;libID=3788579",
};

export const countryCodes = [
  { name: "Afghanistan", code: "AF", dial_code: "+93" },
  { name: "Albania", code: "AL", dial_code: "+355" },
  { name: "Algeria", code: "DZ", dial_code: "+213" },
  { name: "Andorra", code: "AD", dial_code: "+376" },
  { name: "Angola", code: "AO", dial_code: "+244" },
  { name: "Antigua and Barbuda", code: "AG", dial_code: "+1-268" },
  { name: "Argentina", code: "AR", dial_code: "+54" },
  { name: "Armenia", code: "AM", dial_code: "+374" },
  { name: "Australia", code: "AU", dial_code: "+61" },
  { name: "Austria", code: "AT", dial_code: "+43" },
  { name: "Azerbaijan", code: "AZ", dial_code: "+994" },
  { name: "Bahamas", code: "BS", dial_code: "+1-242" },
  { name: "Bahrain", code: "BH", dial_code: "+973" },
  { name: "Bangladesh", code: "BD", dial_code: "+880" },
  { name: "Barbados", code: "BB", dial_code: "+1-246" },
  { name: "Belarus", code: "BY", dial_code: "+375" },
  { name: "Belgium", code: "BE", dial_code: "+32" },
  { name: "Belize", code: "BZ", dial_code: "+501" },
  { name: "Benin", code: "BJ", dial_code: "+229" },
  { name: "Bhutan", code: "BT", dial_code: "+975" },
  { name: "Bolivia", code: "BO", dial_code: "+591" },
  { name: "Bosnia and Herzegovina", code: "BA", dial_code: "+387" },
  { name: "Botswana", code: "BW", dial_code: "+267" },
  { name: "Brazil", code: "BR", dial_code: "+55" },
  { name: "Brunei", code: "BN", dial_code: "+673" },
  { name: "Bulgaria", code: "BG", dial_code: "+359" },
  { name: "Burkina Faso", code: "BF", dial_code: "+226" },
  { name: "Burundi", code: "BI", dial_code: "+257" },
  { name: "Cambodia", code: "KH", dial_code: "+855" },
  { name: "Cameroon", code: "CM", dial_code: "+237" },
  { name: "Canada", code: "CA", dial_code: "+1" },
  { name: "Cape Verde", code: "CV", dial_code: "+238" },
  { name: "Central African Republic", code: "CF", dial_code: "+236" },
  { name: "Chad", code: "TD", dial_code: "+235" },
  { name: "Chile", code: "CL", dial_code: "+56" },
  { name: "China", code: "CN", dial_code: "+86" },
  { name: "Colombia", code: "CO", dial_code: "+57" },
  { name: "Comoros", code: "KM", dial_code: "+269" },
  { name: "Congo", code: "CG", dial_code: "+242" },
  { name: "Costa Rica", code: "CR", dial_code: "+506" },
  { name: "Croatia", code: "HR", dial_code: "+385" },
  { name: "Cuba", code: "CU", dial_code: "+53" },
  { name: "Cyprus", code: "CY", dial_code: "+357" },
  { name: "Czech Republic", code: "CZ", dial_code: "+420" },
  { name: "Denmark", code: "DK", dial_code: "+45" },
  { name: "Djibouti", code: "DJ", dial_code: "+253" },
  { name: "Dominican Republic", code: "DO", dial_code: "+1-809" },
  { name: "Ecuador", code: "EC", dial_code: "+593" },
  { name: "Egypt", code: "EG", dial_code: "+20" },
  { name: "El Salvador", code: "SV", dial_code: "+503" },
  { name: "Estonia", code: "EE", dial_code: "+372" },
  { name: "Ethiopia", code: "ET", dial_code: "+251" },
  { name: "Finland", code: "FI", dial_code: "+358" },
  { name: "France", code: "FR", dial_code: "+33" },
  { name: "Germany", code: "DE", dial_code: "+49" },
  { name: "Greece", code: "GR", dial_code: "+30" },
  { name: "India", code: "IN", dial_code: "+91" },
  { name: "Indonesia", code: "ID", dial_code: "+62" },
  { name: "Italy", code: "IT", dial_code: "+39" },
  { name: "Japan", code: "JP", dial_code: "+81" },
  { name: "Mexico", code: "MX", dial_code: "+52" },
  { name: "Netherlands", code: "NL", dial_code: "+31" },
  { name: "New Zealand", code: "NZ", dial_code: "+64" },
  { name: "Pakistan", code: "PK", dial_code: "+92" },
  { name: "Philippines", code: "PH", dial_code: "+63" },
  { name: "Russia", code: "RU", dial_code: "+7" },
  { name: "South Africa", code: "ZA", dial_code: "+27" },
  { name: "South Korea", code: "KR", dial_code: "+82" },
  { name: "Spain", code: "ES", dial_code: "+34" },
  { name: "Sweden", code: "SE", dial_code: "+46" },
  { name: "Switzerland", code: "CH", dial_code: "+41" },
  { name: "Thailand", code: "TH", dial_code: "+66" },
  { name: "Turkey", code: "TR", dial_code: "+90" },
  { name: "United Kingdom", code: "GB", dial_code: "+44" },
  { name: "United States", code: "US", dial_code: "+1" },
  { name: "Vietnam", code: "VN", dial_code: "+84" },
];

export const Status = [
  { name: "Run and Drive", value: "run_and_drives", color: "green" },
  { name: "For Repair", value: "for_repair", color: "orange" },
  { name: "To Be Dismantled", value: "to_be_dismantled", color: "red" },
  { name: "Not Run", value: "not_run", color: "volcano" },
  { name: "Used", value: "used", color: "geekblue" },
  { name: "Unconfirmed", value: "unconfirmed", color: "purple" },
  { name: "Engine Starts", value: "engine_starts", color: "cyan" },
  { name: "Enhanced", value: "enhanced", color: "gold" },
  { name: "Enhanced", value: "undefined", color: "secondary" },
];

export const filterItems = {
  Auction: [
    { name: "Copart", color: "blue-600", type: "select", domain_id: 3 },
    { name: "IAAI", color: "red-600", type: "select", domain_id: 1 },
  ],
  Condition: [
    {
      name: "Run And Drive",
      value: 0,
    },
    {
      name: "For Repair",
      value: 1,
    },
    {
      name: "To Be Dismantled",
      value: 2,
    },
    {
      name: "Not Run",
      value: 3,
    },
    {
      name: "Used",
      value: 4,
    },
    {
      name: "Unconfirmed",
      value: 5,
    },
    {
      name: "Engine Starts",
      value: 6,
    },
    {
      name: "Enhanced",

      value: 7,
    },
  ],
  Transmission: [
    {
      name: "Manual",
      value: 1,
    },
    {
      name: "Automatic",
      value: 2,
    },
  ],
  FuelType: [
    {
      name: "Diesel",
      value: 1,
    },
    {
      name: "Electric",
      value: 2,
    },
    {
      name: "Hybrid",
      value: 3,
    },
    {
      name: "Gasoline",
      value: 4,
    },
    {
      name: "Gas",
      value: 5,
    },
    {
      name: "Flexible",
      value: 6,
    },
    {
      name: "Hydrogen",
      value: 7,
    },
  ],
  Colors: [
    {
      name: "Silver",
      value: 1,
    },
    {
      name: "Purple",
      value: 2,
    },
    {
      name: "Orange",
      value: 3,
    },
    {
      name: "Green",
      value: 4,
    },
    {
      name: "Red",
      value: 5,
    },
    {
      name: "Gold",
      value: 6,
    },
    {
      name: "Charcoal",
      value: 7,
    },
    {
      name: "Brown",
      value: 8,
    },
    {
      name: "Grey",
      value: 9,
    },
    {
      name: "Turquoise",
      value: 10,
    },
    {
      name: "Blue",
      value: 11,
    },
    {
      name: "Bronze",
      value: 12,
    },
    {
      name: "White",
      value: 13,
    },
    {
      name: "Cream",
      value: 14,
    },
    {
      name: "Black",
      value: 15,
    },
    {
      name: "Yellow",
      value: 16,
    },
    {
      name: "Beige",
      value: 17,
    },
    {
      name: "Pink",
      value: 18,
    },
  ],
  Seller: [
    { name: "360 Insurance Company", value: 399 },
    { name: "7 Stars Autos LLC", value: 684 },
    { name: "AAA Hawaii", value: 377 },
    { name: "AAA Insurance", value: 609 },
    { name: "AAA Missouri", value: 240 },
    { name: "AAA New Mexico", value: 357 },
    { name: "AAA Northern New England", value: 278 },
    { name: "AAA Ohio", value: 315 },
    { name: "AAA Pennsylvania", value: 274 },
    { name: "AAA Rhode Island", value: 348 },
    { name: "AAA So California", value: 277 },
    { name: "AAA Texas", value: 251 },
    { name: "AAA Tidewater VA", value: 390 },
    { name: "AAA West Virginia", value: 462 },
    { name: "ABILENE TEACHERS C.U.", value: 666 },
    { name: "ACCC Insurance", value: 576 },
    { name: "Acuity Insurance", value: 444 },
    { name: "ADESA - Golden Gate/Santander - INACTIVE", value: 595 },
    { name: "Advanced Remarketing Services - ACH", value: 316 },
    { name: "AERO CORPORATION", value: 1084 },
  ],
  BodyStyle: [
    { name: "Sedan", value: 1 },
    { name: "Wagon", value: 2 },
    { name: "Coupe", value: 3 },
    { name: "Pickup", value: 4 },
    { name: "Suv", value: 5 },
    { name: "Cabrio", value: 6 },
    { name: "Van", value: 7 },
    { name: "Moto", value: 8 },
    { name: "Furgon", value: 9 },
    { name: "Combi", value: 10 },
    { name: "Hatchback", value: 11 },
    { name: "Roadster", value: 12 },
    { name: "Limousine", value: 13 },
    { name: "Truck", value: 14 },
    { name: "Bike", value: 15 },
    { name: "Sport bike", value: 16 },
    { name: "Roadster bike", value: 17 },
    { name: "Industrial", value: 18 },
    { name: "Bus", value: 19 },
    { name: "Liftback", value: 20 },
    { name: "Enduro bike", value: 21 },
    { name: "Hearse", value: 22 },
    { name: "Fire truck", value: 23 },
    { name: "Garbage", value: 24 },
    { name: "Trailer", value: 25 },
    { name: "Tandem", value: 26 },
    { name: "Sport car", value: 27 },
    { name: "Other", value: 28 },
  ],
  Location: [
    { name: "10005 crazy horse dr", value: 257 },
    { name: "1000 armstrong dr", value: 441 },
    { name: "1000 auction ln", value: 747 },
    { name: "1000 bethel dr", value: 964 },
    { name: "1000 bethel drive", value: 330 },
    { name: "1000 e gowan rd", value: 962 },
    { name: "1001 - 1st avenue nw", value: 979 },
    { name: "10038 live oaks ave", value: 1227 },
    { name: "100 auction way", value: 475 },
    { name: "100  auction way", value: 3543 },
    { name: "100 industrial way", value: 222 },
    { name: "10100 windisch rd", value: 341 },
    { name: "10131 garrymore lane", value: 512 },
    { name: "10131 garrymore ln", value: 5726 },
    { name: "1015 somerset rd", value: 1624 },
    { name: "101 broadway street s", value: 1996 },
    { name: "101 highway 404", value: 834 },
    { name: "101 hwy 404", value: 232 },
    { name: "101 w.h. lincoln industrial dr", value: 1475 },
    { name: "1021 chemin st louis", value: 1974 },
    { name: "1024 12th st", value: 5296 },
    { name: "10390 sadisco drive", value: 219 },
    { name: "103 thompson st", value: 389 },
    { name: "103  thompson street", value: 1451 },
    { name: "1045 atlanta hwy se", value: 358 },
    { name: "1046 a e moore road", value: 770 },
    { name: "10475 somerset rd", value: 521 },
    { name: "10475 somerset road", value: 905 },
    { name: "10498 n vancouver way", value: 498 },
    { name: "1050 carr 865", value: 914 },
    { name: "10680 charter oak ranch rd", value: 787 },
    { name: "1070 se 9th ter", value: 3610 },
    { name: "10781 highway 707", value: 5886 },
    { name: "107 louis-philipe street", value: 1192 },
    { name: "10910 fm 2920 rd", value: 4482 },
    { name: "10 auction drive", value: 472 },
    { name: "10 halekauila st", value: 2070 },
    {
      name: "10 miles west of lloydminster on hwy 16 compound 2 miles west of loydminster on hwy 16",
      value: 2192,
    },
    { name: "11003 us highway 64", value: 4483 },
    { name: "1100 s york st", value: 1115 },
    { name: "1100 w blancke st", value: 3569 },
    { name: "11018 n interstate 35", value: 2299 },
    { name: "1102 s main st", value: 1724 },
    { name: "1102 spencer hwy", value: 3421 },
    { name: "1106 e gurley st", value: 2091 },
    { name: "110 english crescent", value: 980 },
    { name: "11101 n congress ave", value: 735 },
    { name: "11150 s.fm 1541", value: 308 },
    { name: "1118 west craighead rd", value: 2088 },
    { name: "11221 highway 90", value: 476 },
    { name: "1122 e 34th st", value: 768 },
    { name: "11275  south zarzamora", value: 2682 },
    { name: "11275 s zarzamora st", value: 294 },
    { name: "112 georgetown dr", value: 1888 },
    { name: "11302 6th avenue", value: 1219 },
    { name: "11385 g avenue", value: 329 },
    { name: "11499 douglas rd.", value: 384 },
    { name: "114 reimer rd", value: 1989 },
    { name: "114 school ground rd", value: 1623 },
    { name: "1155 kenmount rd", value: 977 },
    { name: "1155 n eldon ave", value: 302 },
    { name: "11600 fruehauf dr", value: 2335 },
    { name: "1169 us-130", value: 290 },
    { name: "116 bridge street e.", value: 592 },
    { name: "11711 technology dr", value: 817 },
    { name: "11713 highway 64", value: 758 },
    { name: "118 farrington ave", value: 754 },
    { name: "11950 fl-82", value: 394 },
    { name: "119 jahn street", value: 2191 },
    { name: "11 sabrina way", value: 2893 },
    { name: "12056 pth31 darlinford", value: 2194 },
    { name: "1208 17th st. east", value: 1481 },
    { name: "1208  17th street east", value: 664 },
    { name: "1208 17th street east", value: 353 },
    { name: "1209 s bailey st", value: 2156 },
    { name: "120 hickory st", value: 523 },
    { name: "1210 kings road", value: 396 },
    { name: "1210  kings road", value: 659 },
    { name: "1215 chemin du grand bernier sud", value: 686 },
    { name: "1215 industriel", value: 624 },
    { name: "12200 main rd", value: 573 },
    { name: "12305 long beach blvd", value: 1906 },
    { name: "1235 s 3200 w", value: 931 },
    { name: "1239 n boulder hwy", value: 251 },
    { name: "1239  north boulder hwy, ste 900", value: 2380 },
    { name: "123 four wheel dr", value: 387 },
    { name: "12403 james madison hwy", value: 792 },
    { name: "12420 73rd ct", value: 5797 },
    { name: "1250 e main st", value: 399 },
    { name: "125 old highway 138", value: 236 },
    { name: "12700 nw 42nd ave", value: 960 },
    { name: "1278 highway 9 byp e", value: 2362 },
    { name: "12808 w greenway rd", value: 1108 },
    { name: "1280 highway 50", value: 503 },
    { name: "1280 jackson street", value: 354 },
    { name: "12903 old richmond rd", value: 1717 },
    { name: "12 main street", value: 1249 },
    { name: "1-300 sky blvd", value: 973 },
    // ... add more as needed ...
  ],
  PrimaryDamage: [
    { name: "All Over", value: 33 },
    { name: "Biohazard", value: 56 },
    { name: "Bio Hazard", value: 87 },
    { name: "Biohazard/Chemical", value: 72 },
    { name: "Burn", value: 80 },
    { name: "Burn - Engine", value: 83 },
    { name: "Burn - Interior", value: 81 },
    { name: "Cash For Clunkers", value: 82 },
    { name: "Charity", value: 90 },
    { name: "Damage History", value: 27 },
    { name: "Dh8635", value: 13648 },
    { name: "Dh8636", value: 13303 },
    { name: "Dh8637", value: 13331 },
    { name: "Dh9217", value: 12364 },
    { name: "Dh9218", value: 12618 },
    { name: "Dh9219", value: 13360 },
    { name: "Dh9220", value: 13269 },
    { name: "Dh9221", value: 12509 },
    { name: "Dh9222", value: 12731 },
    { name: "Dh9223", value: 12498 },
    { name: "Dh9224", value: 12519 },
    { name: "Dh9225", value: 12467 },
    { name: "Dh9227", value: 12692 },
    { name: "Dh9229", value: 12499 },
    { name: "Dh9230", value: 12421 },
    { name: "Dh9231", value: 12395 },
    { name: "Dh9232", value: 12385 },
    { name: "Dh9234", value: 12387 },
    { name: "Dh9235", value: 12492 },
    { name: "Dh9236", value: 12426 },
    { name: "Dh9237", value: 12391 },
    { name: "Dh9238", value: 12533 },
    { name: "Dh9239", value: 12436 },
    { name: "Dh9241", value: 14069 },
    { name: "Dh9242", value: 12535 },
    { name: "Dh9244", value: 12394 },
    { name: "Dh9245", value: 12461 },
    { name: "Dh9246", value: 12390 },
    { name: "Dh9247", value: 12725 },
    { name: "Dh9248", value: 13795 },
    { name: "Dh9249", value: 13814 },
    { name: "Dh9264", value: 12383 },
    { name: "Dh9277", value: 12579 },
    { name: "Dh9279", value: 12412 },
    { name: "Dh9359", value: 12376 },
    { name: "Dh9371", value: 12549 },
    { name: "Dh9375", value: 12382 },
    { name: "Dh9376", value: 12406 },
    { name: "Dh9413", value: 12576 },
    { name: "Dh9450", value: 12523 },
    { name: "Dh9453", value: 12444 },
    { name: "Dh9454", value: 12505 },
  ],
  Cylinders: Array.from({ length: 12 }, (_, i) => {
    const num = 12 - i;
    return { name: num.toString(), value: num };
  }),
};
